### ISSUE TITLE
Highlighted card title after click-to-expand.

### ISSUE THREAD

**Issue by niconomaa** [HendrikSchmidt/strassenlaerm#1]
Bug?
After clicking on a card and expanding it (or closing it) the card's title is highlighted which looks a bit off (especially when closed) 
<img width="549" alt="Screenshot 2021-03-07 at 20 12 03" src="https://user-images.githubusercontent.com/9486619/110253284-652eb280-7f81-11eb-8f9a-9561f57f54ad.png">

Chrome Version 88.0.4324.192 (Official Build) (x86_64)

**Comment by HendrikSchmidt** [comment]
This is a accessibility Success Criterion:
[Understanding SC 2.4.7](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html)
[The Accessibility Requirement You’re Probably Failing Right Now: Focus States](https://truematter.medium.com/the-accessibility-requirement-youre-probably-failing-right-now-focus-states-778b61879f02)

But I'll try to pretty it up a bit :)
